version: "3.9"

services:
  nats:
    image: nats:2.11-alpine
    container_name: nats
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  postgres_source:
    image: postgres:16-alpine
    container_name: postgres_source
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_source_data:/var/lib/postgresql/data
      - ./init/db_source:/docker-entrypoint-initdb.d

  postgres_reciever:
    image: postgres:16-alpine
    container_name: postgres_reciever
    environment:
      POSTGRES_DB: target_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_reciever_data:/var/lib/postgresql/data
      - ./init/db_reciever:/docker-entrypoint-initdb.d

volumes:
  postgres_source_data:
  postgres_reciever_data:
